<?php

namespace AppBundle\Repository;

/**
 * StatusModeratorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusModeratorRepository extends \Doctrine\ORM\EntityRepository
{
}
