app_article:
    resource: "@AppBundle/Controller/ArticleController.php"
    type:     annotation

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /blog/

app:
    resource: '@AppBundle/Controller/'
    type: annotation
