#app_status_moderator:
#    resource: "@AppBundle/Controller/StatusModeratorController.php"
#   type:     annotation

#app_user:
#    resource: "@AppBundle/Controller/UserController.php"
#    type:     annotation

#app_category:
#   resource: "@AppBundle/Controller/CategoryController.php"
#   type:     annotation

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /blog/

app:
    resource: '@AppBundle/Controller/'
    type: annotation
